version: '3.8'

services:
  eureka-service:
    build:
      context: eureka-service/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - ridesharing-network
  config-service:
    build:
      context: config-service/
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    restart: always
    networks:
      - ridesharing-network
    environment:
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
  gateway-service:
    build:
      context: gateway-service/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    networks:
      - ridesharing-network
    depends_on:
      - eureka-service
      - config-service
  gps-service:
    build:
      context: gps-service/
      dockerfile: Dockerfile
    restart: always
    networks:
      - ridesharing-network
    depends_on:
      - eureka-service
      - gateway-service
      - config-service
    environment:
      GEOCODE_API_KEY: ${GEOCODE_API_KEY}
  dynamic-billing-service:
    build:
      context: dynamic-delta-billing-service/
      dockerfile: Dockerfile
    restart: always
    networks:
      - ridesharing-network
    depends_on:
      - eureka-service
      - gateway-service
      - config-service
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
  payment-service:
    build:
      context: payment-service/
      dockerfile: Dockerfile
    restart: always
    networks:
      - ridesharing-network
    depends_on:
      - eureka-service
      - gateway-service
      - config-service
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}

# Networks to be created to facilitate communication between containers
networks:
  ridesharing-network:
