spring:
  application:
    name: ride-planner-service
  profiles:
    active: prod
  r2dbc:
    url: r2dbc:postgresql://192.168.1.144:5432/ride_sharing
    username: postgres
    password: mysecretpassword
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - kafka:9092
      bindings:
        output:
          binder: kafka
          destination: ride-planning-topic
          content-type: text/plain
      producer:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

server.port: 0
