version: 2.1
machine: true
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
      
    steps:
      - checkout
      - save_cache:
          key: mvn_cache
          paths:
            - ~/.m2
      - run: ./mvnw clean verify
      - store_artifacts:
          path: ~/test-results/rspec/
      - restore_cache:
          key: mvn_cache
          

