version: 2.1
machine: true
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version
      - checkout
      - save_cache:
          key: mvn_cache
          paths:
            - ~/.m2
      - run: ./mvnw clean verify sonar:sonar
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - restore_cache:
          key: mvn_cache
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
