version: 2.1
machine: true
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
      
    steps:
      - checkout
      - save_cache:
          key: mvn_cache
          paths:
            - ~/.m2
      - run: ./mvnw clean verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - restore_cache:
          key: mvn_cache
          

