version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
      
    steps:
      - checkout
      - save_cache:
          key: mvn_cache
          paths:
            - ~/.m2
      - run: ./mvnw clean install
      - restore_cache:
          key: mvn_cache

