spring:
  application:
    name: gps-position-tracker-service
  profiles:
    active: prod
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - kafka:9092
      bindings:
        output:
          binder: kafka
          destination: gps-position-topic
          content-type: text/plain
      producer:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

server.port: 0
