eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.168.1.144:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: gps_service_route
          uri: lb://gps-service
          predicates:
            - Path=/geocode/**

server.port: 8082
