spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://config-service:8012
      name: config-service
      failFast: true
      retry:
        maxAttempts: 20

server.port: 8082
