eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery.enabled: true
    gateway:
      routes:
        - id: gps_service_route
          uri: lb://gps-service
          predicates:
            - Path=/geocode/**
        - id: dynamic_billing_service_route
          uri: lb://dynamic-billing-service
          predicates:
            - Path=/dynamic-billing-service/**
        - id: payment_service_route
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: gps_tracker_service_route
          uri: lb://gps-tracker-service
          predicates:
            - Path=/gps-receiver/**
        - id: ride_planner_service_route
          uri: lb://ride-planner-service
          predicates:
            - Path=/rides/**

server.port: 8082
management.endpoints.web.exposure.include: gateway
