spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://config-server:8012
      name: config-server
      failFast: true
      retry:
        maxAttempts: 20

server.port: 8082
