STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
connection.pool.size: 20

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.168.1.144:8761/eureka/

spring:
  application:
    name: payment-service

server.port: 0
