spring:
  application:
    name: dynamic-billing-service
  r2dbc:
    url: r2dbc:postgresql://192.168.1.144:5432/pending_rides
    username: postgres
    password: mysecretpassword
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        output:
          binder: kafka
          destination: DELTA_BILLING_FINISHED
          content-type: text/plain
      producer:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.apache.kafka.common.serialization.StringSerializer

rest.api:
  endpoint: http://api.weatherstack.com/current
  key: ${WEATHER_API_KEY}
  output: json

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

server.port: 0
