gps.rest.api:
  endpoint: http://api.positionstack.com/v1/reverse
  key: ${GEOCODE_API_KEY}
  output: json

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.168.1.144:8761/eureka/

spring:
  application:
    name: gps-service
