server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      base-path: /manage
  server:
    port: 8081
