spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cdinescu/ride-sharing-central-config
          username: cdinescu
          password: ${GIT_ACCESS_TOKEN}
          clone-on-start: true
          searchPaths: gateway-service
server:
  port: 8012
