spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cdinescu/ride-sharing-central-config
          username: cdinescu
          password: ${GIT_ACCESS_TOKEN}
          clone-on-start: true
          searchPaths: {application}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

server:
  port: 8012

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true

logging.level.org.springframework:
  cloud: debug
  web: debug
